### ISSUE TITLE
Only supports convolution kernels of 7*7 size?

### ISSUE THREAD

**Issue by MicroZHY** [microsoft/ConvStencil#5]
In the code provided, it looks like it only supports convolution kernels of 7x7 size. I don't know if I'm reading it wrong or if that's indeed the case. For example, in the 2D source file, I only see code where the convolution kernel is fixed to 7x7 size.

**Comment by Akemiiii** [comment]
Sorry for the late reply. Yes. For the 3x3 kernel size, we temporarily fuse it into a 7x7 kernel. We will increase the supported kernel size in the coming months to make ConvStencil more practical.

**Comment by MicroZHY** [comment]
您好！您的邮件已收悉，谢谢常联系哦饮水思源

**Comment by MicroZHY** [comment]
Thank you for your guidance. If I understand correctly, your current support is limited to only 3x3 and 7x7 kernel sizes, right? Are kernel sizes like 5x5 and 6x6 supported as well, or is it the case that any size smaller than 7x7 is acceptable?

**Comment by MicroZHY** [comment]
> Sorry for the late reply. Yes. For the 3x3 kernel size, we temporarily fuse it into a 7x7 kernel. We will increase the supported kernel size in the coming months to make ConvStencil more practical.

Thank you for your guidance. If I understand correctly, your current support is limited to only 3x3 and 7x7 kernel sizes, right? Are kernel sizes like 5x5 and 6x6 supported as well, or is it the case that any size smaller than 7x7 is acceptable?

**Comment by Akemiiii** [comment]
> > Sorry for the late reply. Yes. For the 3x3 kernel size, we temporarily fuse it into a 7x7 kernel. We will increase the supported kernel size in the coming months to make ConvStencil more practical.
> 
> Thank you for your guidance. If I understand correctly, your current support is limited to only 3x3 and 7x7 kernel sizes, right? Are kernel sizes like 5x5 and 6x6 supported as well, or is it the case that any size smaller than 7x7 is acceptable?

Thank you for your follow-up. Our algorithm does not limit the size of the kernel. Currently, we have not fully implemented kernels of other sizes, such as 5x5 and 6x6, which is the work we are doing now, as I mentioned above.

**Comment by MicroZHY** [comment]
> > > Sorry for the late reply. Yes. For the 3x3 kernel size, we temporarily fuse it into a 7x7 kernel. We will increase the supported kernel size in the coming months to make ConvStencil more practical.
> > 
> > 
> > Thank you for your guidance. If I understand correctly, your current support is limited to only 3x3 and 7x7 kernel sizes, right? Are kernel sizes like 5x5 and 6x6 supported as well, or is it the case that any size smaller than 7x7 is acceptable?
> 
> Thank you for your follow-up. Our algorithm does not limit the size of the kernel. Currently, we have not fully implemented kernels of other sizes, such as 5x5 and 6x6, which is the work we are doing now, as I mentioned above.

Thanks for the guidance, I understand exactly what you mean.
